### ISSUE TITLE
Problem running code on colab.

### ISSUE THREAD

**Issue by hniksoleimani** [computational-imaging/automatic-integration#4]
Greeting, I tried to run your code in colab but unfortunately couldnt figure out the error that is displayed when running the last cell.

![Untitled](https://user-images.githubusercontent.com/94698402/163807437-a0445501-114f-450a-8b50-93c454cc1ff4.png)

**Comment by davelindell** [comment]
Sorry for the long delay on this. There was a typo in the function call, which I've fixed. The colab now runs without errors.
