### ISSUE TITLE
2D and 3D case.

### ISSUE THREAD

**Issue by elientumba2019** [computational-imaging/automatic-integration#6]
Hi dear authors and thanks for such fantastic work. 

Could you please guide me on how one might use, or extend the autoint framework for 2d and 3d integration?
One use case for the 2d case might be fitting the derivative network to an image.

Thank you.

@davelindell
@wetzste1

**Comment by davelindell** [comment]
Hi elientumba2019,

We currently only support 1D integration in the codebase, but it is possible to extend this framework for 2D integration (similar to integral images) and 3D integration as we describe in the [supplement of the paper](https://arxiv.org/pdf/2012.01714.pdf): "Multivariable integration with autoint".
