### ISSUE TITLE
Ambiguity of coordinate for gradient net

### ISSUE THREAD

**Issue by Yuliang-Huang** [computational-imaging/automatic-integration#7]
Dear authors,

Thanks for sharing your great work. I am wondering how you address the problem of the same voxel represented by multiple input coordinates when training the gradient net.
Taking the CT sinogram as an example, the input for the gradient net in your paper is (ρ, α, t). I guess this is because only in this way the partial derivative against t can give you the CT number at each point. My question is, the same voxel may have different coordinates when ρ and α change. This will cause problem when trying to inferring the CT number by the gradient net. Since different coordinates may actually link to the same point, you may get inconsistent values when inferring the CT number at the same point.
Thanks in advance if you could provide your thoughts.

Best Regards,
Yuliang

**Comment by davelindell** [comment]
Hi Yuliang, 

Thanks for the question. This is something we looked into, but I didn't come up with a satisfactory answer for how to do this in two dimensions. Basically, you'd like AutoInt to integrate along the ray, so the derivative network needs to be created with respect to the ray parameter. Then you need two other parameters to define the ray position and orientation. So you will always have this issue as far as I can tell. 

One other thing is that for CT reconstruction, you care more about the inverse problem--so if you train AutoInt for this you end up learning the integral, which gives you the measurements (not the volume). A more straightforward thing to do in this case, is just to parameterize the unknown volume with a neural network, query the network to get samples along the rays, and then compute the ray integral using Monte Carlo integration. If you enforce that the output of the integration is consistent with the CT measurements, the network should solve the inverse problem.

Hope that helps.

David
